version: '3.1'

services:
  db:
    image: mysql
    command: --mysql-native-password=ON
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d

volumes:
  db_data: